version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
    install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH $HOME/.local/bin/uv sync --locked --no-dev --group docs
